export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_START = 'FETCH_PRODUCT_START';
export const FETCH_PRODUCT_FAILED = 'FETCH_PRODUCT_FAILED';
export const SET_PRODUCT_LIST = 'SET_PRODUCT_LIST';
